services:

    metronic.header_builder:
        class: Randock\MetronicBundle\HeaderBuilder\HeaderBuilder
        arguments:
            - '@service_container'

    metronic.getheaderlist.function:
        class: Randock\MetronicBundle\HeaderBuilder\Twig\MetronicHeaderBuilderExtension
        arguments:
            - '@metronic.header_builder'
        tags:
            - { name: twig.extension }

    metronic.menu_builder:
        class: Randock\MetronicBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@service_container"


    metronic.top_menu:
        class: Knp\Menu\MenuItem
        public: true
        factory: ["@metronic.menu_builder", createTopMenu]
        arguments: ["@request_stack"]
        tags:
            - {name: knp_menu.menu, alias: topMenu}

    metronic.main_menu:
        class: Knp\Menu\MenuItem
        public: true
        factory: ["@metronic.menu_builder", createMainMenu]
        arguments: ["@request_stack"]
        tags:
            - {name: knp_menu.menu, alias: mainMenu}
